### ISSUE TITLE
Hackmoney 2020 follow up

### ISSUE THREAD

**Issue by PatrickAlphaC** [tommymsz006/artdefi-ui#1]
Hi TL! 

Just wanted to reach out and say thank you for submitting to Chainlink and participating in such an awesome hackathon! I'd love to get your thoughts and feedback on the hackathon, your chainlink integration, and where you see yourself going from this project. Are you free at all in the next few days for a 20 minute chat?

In any case, let me know!

**Comment by tommymsz006** [comment]
Hi Patrick,

Sorry for late reply. Due to timezone difference, it may be a bit tricky,
but here is some written feedback below for your quick reference:

I heard of Chainlink 1.5 years ago in another hackathon but didn't have a
chance to use it (given my limited blockchain knowledge at that time).

I used Chainlink to integrate with TheGraph so that I can get the
historical data in smart contract. It took a bit of time to get up to speed
by running my own node, playing around with a few examples, etc. Once I've
tried it out everything (i.e. do I need to write my own external adapters?
do I need to run my own node? etc.), I can then easily understand the
components needed for the given use case.I finally went for a simpler
approach by using an existing node that is able to perform "HttpPost" &
"ETHBytes32", which solved my problem.

I primarily built my project in Kovan network and it worked like a chime,
after the above studying was done. Overall it was a good experience.

One minor suggestion I had: I think a landing page (for beginners) that can
describe the need of different components (existing decentralized oracles,
vs the need to build external adopter, vs the need of running its own node,
etc.) in different use cases would be even more helpful so that developers
can get onboarded even quicker.

Hope these help.

Tommy

**Comment by PatrickAlphaC** [comment]
That is helpful, thank you Tommy! And ah, yes the timezone thing is a bit tricky, if this works for you we appreciate the feedback! 

Woah you spun up your own node! That's impressive. Have you checked out our discord? Generally, if you go to the node operators channel and ask someone to spin up a custom job for you, someone will. Or you can just ping me directly too. Glad you found the generic httpget/post jobs. 

Could I also ask how you decided to use the Chainlink oracle? As in, what were some of the other oracles you looked into and how'd you end up using CL?

**Comment by tommymsz006** [comment]
Thanks for the information. I will continue to look out for discord.

Re: why I ended up using CL. First of all, I was impressed by the Chainlink
presentation back in another hackathon by ETHGlobal (ETH San Francisco).
It's glad that CL also appeared in this hackathon and this made it an
obvious choice. Secondly, and more importantly, given different DeFi
attacks this year (e.g. bZX one in Feb), one improvement solution is also
the use of decentralized oracles and CL was also mentioned couple times. I
believe this increased the developers' confidence. In addition, I believe
the new deliverable, like VRF used by PoolTogether, continued to
position CL as great partner for growing blockchain projects.

Tommy

**Comment by PatrickAlphaC** [comment]
Hi Tommy,

Thanks for your feedback here! It's greatly appreciated. Yes, the project has had a lot of great strengthening events happen recently, I'm glad you took notice.

I'll be looking forward to more projects from you, but in the meantime, thanks again for your feedback.
